version: 2.1

orbs:

  aws-cli: circleci/aws-cli@2.0.3

jobs:

    Create-Infrastructure:
      docker: 
        - image: amazon/aws-cli
      steps:
        - checkout
        - run: 
            name: "Creating Cloudformation Stack"
            command: "aws cloudformation deploy --stack-name Section4 --template-file cloudTemplate.yml --region us-east-1"

    Configure-Infrastructure:
      docker: 
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        - add_ssh_keys:
            fingerprints: ["c4:65:29:ae:25:26:ef:49:25:2d:54:e2:f2:87:40:f0"]
        - run:
            name: "Installing Ansible"
            command: apk add --update ansible
        - run:
            name: "cat playbook"
            command: "cat main4.yml"
        - run:
            name: "cat Inventory"
            command: "cat inventory.txt"    
        - run:
            name: "Configuring Servers"
            command: "ansible-playbook main4.yml -vvv -i inventory.txt" 
workflows: 
  CICD-Workflow:
    jobs:
      - Create-Infrastructure
      - Configure-Infrastructure:
          requires: 
            - Create-Infrastructure