version: 2.1

orbs:

  aws-cli: circleci/aws-cli@2.0.3

jobs:

    Create-Infrastructure:
      docker: 
        - image: amazon/aws-cli
      steps:
        - checkout
        - run: 
            name: "Creating Cloudformation Stack"
            command: "aws cloudformation deploy --stack-name Section4 --template-file cloudTemplate.yml --region us-east-1"

    Configure-Infrastructure:
      docker: 
        - image: python:3.7-alpine3.11
      steps:
        - checkout
        #- add_ssh_keys:
         #   fingerprints: ["34:2f:21:08:4b:27:6d:d0:0a:c1:bd:79:f1:3e:a0:d1"]
        - run:
            name: "Installing Ansible"
            command: apk add --update ansible
        - run:
            name: "cat playbook"
            command: "cat main4.yml"
        - run:
            name: "cating Inventory1"
            command: "ssh ubuntu@3.86.205.237 -i try.pem"    
        - run:
            name: "Configuring Servers"
            command: "ansible-playbook main4.yml -vvv -i inventory.txt --private-key try.pem" 
workflows: 
  CICD-Workflow: 
    jobs:
      - Create-Infrastructure
      - Configure-Infrastructure:
          requires: 
            - Create-Infrastructure